export interface CountryOption {
  code: string; // TradeMap 3-digit ISO numeric code
  name: string;
  flag: string;
}

export const TOP_TRADE_COUNTRIES: CountryOption[] = [
  { code: "000", name: "World", flag: "🌍" },
  { code: "699", name: "India", flag: "🇮🇳" },
  { code: "156", name: "China", flag: "🇨🇳" },
  { code: "842", name: "United States", flag: "🇺🇸" },
  { code: "276", name: "Germany", flag: "🇩🇪" },
  { code: "784", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "704", name: "Vietnam", flag: "🇻🇳" },
  { code: "826", name: "United Kingdom", flag: "🇬🇧" },
  { code: "392", name: "Japan", flag: "🇯🇵" },
  { code: "410", name: "South Korea", flag: "🇰🇷" },
  { code: "792", name: "Turkey", flag: "🇹🇷" },
  { code: "381", name: "Italy", flag: "🇮🇹" },
  { code: "251", name: "France", flag: "🇫🇷" },
  { code: "124", name: "Canada", flag: "🇨🇦" },
  { code: "036", name: "Australia", flag: "🇦🇺" },
  { code: "076", name: "Brazil", flag: "🇧🇷" },
  { code: "682", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "360", name: "Indonesia", flag: "🇮🇩" },
  { code: "050", name: "Bangladesh", flag: "🇧🇩" },
  { code: "724", name: "Spain", flag: "🇪🇸" },
  { code: "528", name: "Netherlands", flag: "🇳🇱" },
  { code: "764", name: "Thailand", flag: "🇹🇭" },
  { code: "586", name: "Pakistan", flag: "🇵🇰" },
  { code: "458", name: "Malaysia", flag: "🇲🇾" },
  { code: "702", name: "Singapore", flag: "🇸🇬" },
  { code: "484", name: "Mexico", flag: "🇲🇽" },
  { code: "710", name: "South Africa", flag: "🇿🇦" },
  { code: "643", name: "Russia", flag: "🇷🇺" },
  { code: "818", name: "Egypt", flag: "🇪🇬" },
  { code: "616", name: "Poland", flag: "🇵🇱" },
  { code: "056", name: "Belgium", flag: "🇧🇪" },
  { code: "756", name: "Switzerland", flag: "🇨🇭" },
  { code: "752", name: "Sweden", flag: "🇸🇪" },
  { code: "608", name: "Philippines", flag: "🇵🇭" },
  { code: "144", name: "Sri Lanka", flag: "🇱🇰" },
];

export const ALL_COUNTRIES: CountryOption[] = [
  ...TOP_TRADE_COUNTRIES,
  { code: "004", name: "Afghanistan", flag: "🇦🇫" },
  { code: "008", name: "Albania", flag: "🇦🇱" },
  { code: "012", name: "Algeria", flag: "🇩🇿" },
  { code: "020", name: "Andorra", flag: "🇦🇩" },
  { code: "024", name: "Angola", flag: "🇦🇴" },
  { code: "028", name: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "032", name: "Argentina", flag: "🇦🇷" },
  { code: "051", name: "Armenia", flag: "🇦🇲" },
  { code: "040", name: "Austria", flag: "🇦🇹" },
  { code: "031", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "044", name: "Bahamas", flag: "🇧🇸" },
  { code: "048", name: "Bahrain", flag: "🇧🇭" },
  { code: "052", name: "Barbados", flag: "🇧🇧" },
  { code: "112", name: "Belarus", flag: "🇧🇾" },
  { code: "084", name: "Belize", flag: "🇧🇿" },
  { code: "204", name: "Benin", flag: "🇧🇯" },
  { code: "064", name: "Bhutan", flag: "🇧🇹" },
  { code: "068", name: "Bolivia", flag: "🇧🇴" },
  { code: "070", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "072", name: "Botswana", flag: "🇧🇼" },
  { code: "096", name: "Brunei", flag: "🇧🇳" },
  { code: "100", name: "Bulgaria", flag: "🇧🇬" },
  { code: "854", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "108", name: "Burundi", flag: "🇧🇮" },
  { code: "116", name: "Cambodia", flag: "🇰🇭" },
  { code: "120", name: "Cameroon", flag: "🇨🇲" },
  { code: "132", name: "Cape Verde", flag: "🇨🇻" },
  { code: "140", name: "Central African Republic", flag: "🇨🇫" },
  { code: "148", name: "Chad", flag: "🇹🇩" },
  { code: "152", name: "Chile", flag: "🇨🇱" },
  { code: "170", name: "Colombia", flag: "🇨🇴" },
  { code: "174", name: "Comoros", flag: "🇰🇲" },
  { code: "178", name: "Congo", flag: "🇨🇬" },
  { code: "180", name: "DR Congo", flag: "🇨🇩" },
  { code: "188", name: "Costa Rica", flag: "🇨🇷" },
  { code: "384", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "191", name: "Croatia", flag: "🇭🇷" },
  { code: "192", name: "Cuba", flag: "🇨🇺" },
  { code: "196", name: "Cyprus", flag: "🇨🇾" },
  { code: "203", name: "Czech Republic", flag: "🇨🇿" },
  { code: "208", name: "Denmark", flag: "🇩🇰" },
  { code: "262", name: "Djibouti", flag: "🇩🇯" },
  { code: "212", name: "Dominica", flag: "🇩🇲" },
  { code: "214", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "218", name: "Ecuador", flag: "🇪🇨" },
  { code: "222", name: "El Salvador", flag: "🇸🇻" },
  { code: "226", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "232", name: "Eritrea", flag: "🇪🇷" },
  { code: "233", name: "Estonia", flag: "🇪🇪" },
  { code: "231", name: "Ethiopia", flag: "🇪🇹" },
  { code: "242", name: "Fiji", flag: "🇫🇯" },
  { code: "246", name: "Finland", flag: "🇫🇮" },
  { code: "266", name: "Gabon", flag: "🇬🇦" },
  { code: "270", name: "Gambia", flag: "🇬🇲" },
  { code: "268", name: "Georgia", flag: "🇬🇪" },
  { code: "288", name: "Ghana", flag: "🇬🇭" },
  { code: "300", name: "Greece", flag: "🇬🇷" },
  { code: "320", name: "Guatemala", flag: "🇬🇹" },
  { code: "324", name: "Guinea", flag: "🇬🇳" },
  { code: "328", name: "Guyana", flag: "🇬🇾" },
  { code: "332", name: "Haiti", flag: "🇭🇹" },
  { code: "340", name: "Honduras", flag: "🇭🇳" },
  { code: "344", name: "Hong Kong", flag: "🇭🇰" },
  { code: "348", name: "Hungary", flag: "🇭🇺" },
  { code: "352", name: "Iceland", flag: "🇮🇸" },
  { code: "364", name: "Iran", flag: "🇮🇷" },
  { code: "368", name: "Iraq", flag: "🇮🇶" },
  { code: "372", name: "Ireland", flag: "🇮🇪" },
  { code: "376", name: "Israel", flag: "🇮🇱" },
  { code: "388", name: "Jamaica", flag: "🇯🇲" },
  { code: "400", name: "Jordan", flag: "🇯🇴" },
  { code: "398", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "404", name: "Kenya", flag: "🇰🇪" },
  { code: "414", name: "Kuwait", flag: "🇰🇼" },
  { code: "417", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "418", name: "Laos", flag: "🇱🇦" },
  { code: "428", name: "Latvia", flag: "🇱🇻" },
  { code: "422", name: "Lebanon", flag: "🇱🇧" },
  { code: "426", name: "Lesotho", flag: "🇱🇸" },
  { code: "430", name: "Liberia", flag: "🇱🇷" },
  { code: "434", name: "Libya", flag: "🇱🇾" },
  { code: "440", name: "Lithuania", flag: "🇱🇹" },
  { code: "442", name: "Luxembourg", flag: "🇱🇺" },
  { code: "450", name: "Madagascar", flag: "🇲🇬" },
  { code: "454", name: "Malawi", flag: "🇲🇼" },
  { code: "462", name: "Maldives", flag: "🇲🇻" },
  { code: "466", name: "Mali", flag: "🇲🇱" },
  { code: "470", name: "Malta", flag: "🇲🇹" },
  { code: "478", name: "Mauritania", flag: "🇲🇷" },
  { code: "480", name: "Mauritius", flag: "🇲🇺" },
  { code: "498", name: "Moldova", flag: "🇲🇩" },
  { code: "496", name: "Mongolia", flag: "🇲🇳" },
  { code: "499", name: "Montenegro", flag: "🇲🇪" },
  { code: "504", name: "Morocco", flag: "🇲🇦" },
  { code: "508", name: "Mozambique", flag: "🇲🇿" },
  { code: "104", name: "Myanmar", flag: "🇲🇲" },
  { code: "516", name: "Namibia", flag: "🇳🇦" },
  { code: "524", name: "Nepal", flag: "🇳🇵" },
  { code: "554", name: "New Zealand", flag: "🇳🇿" },
  { code: "558", name: "Nicaragua", flag: "🇳🇮" },
  { code: "562", name: "Niger", flag: "🇳🇪" },
  { code: "566", name: "Nigeria", flag: "🇳🇬" },
  { code: "578", name: "Norway", flag: "🇳🇴" },
  { code: "512", name: "Oman", flag: "🇴🇲" },
  { code: "591", name: "Panama", flag: "🇵🇦" },
  { code: "598", name: "Papua New Guinea", flag: "🇵🇬" },
  { code: "600", name: "Paraguay", flag: "🇵🇾" },
  { code: "604", name: "Peru", flag: "🇵🇪" },
  { code: "620", name: "Portugal", flag: "🇵🇹" },
  { code: "634", name: "Qatar", flag: "🇶🇦" },
  { code: "642", name: "Romania", flag: "🇷🇴" },
  { code: "646", name: "Rwanda", flag: "🇷🇼" },
  { code: "686", name: "Senegal", flag: "🇸🇳" },
  { code: "688", name: "Serbia", flag: "🇷🇸" },
  { code: "703", name: "Slovakia", flag: "🇸🇰" },
  { code: "705", name: "Slovenia", flag: "🇸🇮" },
  { code: "706", name: "Somalia", flag: "🇸🇴" },
  { code: "729", name: "Sudan", flag: "🇸🇩" },
  { code: "158", name: "Taiwan", flag: "🇹🇼" },
  { code: "762", name: "Tajikistan", flag: "🇹🇯" },
  { code: "834", name: "Tanzania", flag: "🇹🇿" },
  { code: "788", name: "Tunisia", flag: "🇹🇳" },
  { code: "795", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "800", name: "Uganda", flag: "🇺🇬" },
  { code: "804", name: "Ukraine", flag: "🇺🇦" },
  { code: "858", name: "Uruguay", flag: "🇺🇾" },
  { code: "860", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "862", name: "Venezuela", flag: "🇻🇪" },
  { code: "887", name: "Yemen", flag: "🇾🇪" },
  { code: "894", name: "Zambia", flag: "🇿🇲" },
  { code: "716", name: "Zimbabwe", flag: "🇿🇼" },
];
