# Use Node.js 20 on Debian Bookworm (good balance of size and compatibility)
FROM node:20-bookworm

# Set working directory
WORKDIR /app

# Copy package files first for better layer caching
COPY package.json package-lock.json* ./

# Install npm dependencies
RUN npm install

# Copy Prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

# Install Playwright Chromium and its OS dependencies
RUN npx playwright install --with-deps chromium

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN npm run build

# Set environment variables for Next.js standalone and Hugging Face Spaces port
ENV PORT=7860
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=production

# Expose the port required by Hugging Face Spaces
EXPOSE 7860

# Start the application using the standalone server generated by Next.js
CMD ["node", ".next/standalone/server.js"]
